### ISSUE TITLE
about results

### ISSUE THREAD

**Issue by SakurajimaMaiii** [med-air/DLTTA#1]
我想问下Table 3 里面 **baseline (w/o adaptation)** 的结果， Dataset D和 Datset F 是写反了吗
我按照你们的设置和代码train了一下
结果：
```
Dataset B          C        D        E        F      avg
Dice--- 79.68 73.83 85.01 62.28 67.16  73.59
```
比论文里高一点点，但是D和F貌似差的有点多？
想请教一下您的看法

**Comment by hz0567** [comment]
Hi, thanks for your interest. We have checked the results of Site D and Site F.  The processed data of all six sites are uploaded to the google drive (https://drive.google.com/drive/folders/1yol4sUYh7EtQJzfiPn7mNggypBus1IKM?usp=sharing). You can use them to train the model. The results of the two sites are not reversed.  Please also note that we only evaluate the prostate center region of each case at test time.

**Comment by SakurajimaMaiii** [comment]
Got it. thanks your reply.
