### ISSUE TITLE
About prostate segmentation.

### ISSUE THREAD

**Issue by Asagami-Fujino** [med-air/DLTTA#2]
Thanks for your work. I'm trying to reproduce results on Prostate datasets. But I really don't understand the sentence 'Patches with size of 80x80x80 were cropped as the network inputs.' in the paper. The shape of the MRI volumes is aound [20, 384, 384], which is greatly different from the network input. I'm wondering how to crop the MRI volums into 80x80x80? Looking forward to your reply!

**Comment by hz0567** [comment]
Thanks for your interest. For the prostate dataset, the resolution (in/through plane) is quite different among the six sites. So we conducted re-spacing before cropping the patch. After re-spacing, the shape of the MRI volumes is around [256, 256, 128].

**Comment by Asagami-Fujino** [comment]
Thanks @HongzhengYang, the problem is solved, thanks for your prompt reply :-)

**Comment by indranarendra** [comment]
So we conducted re-spacing before cropping the patch. After re-spacing, the shape of the MRI volumes is around [256, 256, 128].

Can you please explain how this re-spacing is done? I'm also trying to reproduce these results. So, it will be helpful for me if you share the code for this.

**Comment by hz0567** [comment]
Hi, thanks for your interest. I have uploaded the re-spacing code. (https://drive.google.com/drive/folders/14Joa9CstJYkyjNLZwU6bmy4DDgb3XgzE?usp=sharing)
